namespace GeoChemistryNexus.Models
{
    /// <summary>
    /// 图解投点可用的标记形状（含 ScottPlot 内置 + 项目扩展形状）。
    /// </summary>
    public enum PlotMarkerShape
    {
        // ScottPlot 内置
        FilledCircle,
        OpenCircle,
        FilledSquare,
        OpenSquare,
        FilledTriangleUp,
        OpenTriangleUp,
        FilledTriangleDown,
        OpenTriangleDown,
        FilledDiamond,
        OpenDiamond,
        Cross,
        Eks,
        Asterisk,
        VerticalBar,
        HorizontalBar,
        HashTag,
        OpenCircleWithDot,
        OpenCircleWithCross,
        OpenCircleWithEks,
        TriUp,
        TriDown,

        // 项目扩展
        FilledStar,
        OpenStar,
        FilledStar4,
        OpenStar4,
        FilledStar6,
        OpenStar6,
        FilledHexagon,
        OpenHexagon,
        FilledPentagon,
        OpenPentagon,
        FilledOctagon,
        OpenOctagon,
        FilledTriangleLeft,
        OpenTriangleLeft,
        FilledTriangleRight,
        OpenTriangleRight,
        FilledBowtie,
        OpenBowtie,
        FilledHorizontalBowtie,
        OpenHorizontalBowtie,
        FilledParallelogram,
        OpenParallelogram,
        FilledTrapezoid,
        OpenTrapezoid,
        FilledHalfCircleUp,
        OpenHalfCircleUp,
        FilledHalfCircleDown,
        OpenHalfCircleDown,
        FilledHalfCircleLeft,
        OpenHalfCircleLeft,
        FilledHalfCircleRight,
        OpenHalfCircleRight,
        SquareWithCross,
        SquareWithEks,
        SquareWithDot,
        DiamondWithCross,
        DiamondWithDot,
        CircleWithSquare,
        PlusInDiamond,
    }
}
